// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RSoft.Auth.Infra.Data;

namespace RSoft.Auth.Infra.Data.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20220510103734_InitialCreateDb")]
    partial class InitialCreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.AppClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AccessKey")
                        .HasColumnType("char(36)")
                        .HasColumnName("AccessKey");

                    b.Property<ulong>("AllowLogin")
                        .HasColumnType("bit")
                        .HasColumnName("AllowLogin");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit");

                    b.Property<ulong>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(0ul);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("AccessKey")
                        .IsUnique()
                        .HasDatabaseName("AK_AppClient_AccessKey");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("IX_AppClient_ChangedBy");

                    b.HasIndex("ChangedOn")
                        .HasDatabaseName("IX_AppClient_ChangedOn");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_AppClient_CreatedBy");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("IX_AppClient_CreatedOn");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("AK_AppClient_Name");

                    b.ToTable("AppClient");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ApplicationClientId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Description");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit");

                    b.Property<ulong>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(0ul);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationClientId")
                        .HasDatabaseName("IX_Role_ApplicationClientId");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("IX_Role_ChangedBy");

                    b.HasIndex("ChangedOn")
                        .HasDatabaseName("IX_Role_ChangedOn");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_Role_CreatedBy");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("IX_Role_CreatedOn");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("AK_Role_Name");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("BornDate")
                        .IsRequired()
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("ChangedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("ChangedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Document")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Document");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FirstName");

                    b.Property<ulong>("IsActive")
                        .HasColumnType("bit");

                    b.Property<ulong>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(0ul);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("LastName");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("IX_User_ChangedBy");

                    b.HasIndex("ChangedOn")
                        .HasDatabaseName("IX_User_ChangedOn");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("IX_User_CreatedBy");

                    b.HasIndex("CreatedOn")
                        .HasDatabaseName("IX_User_CreatedOn");

                    b.HasIndex("Document")
                        .IsUnique()
                        .HasDatabaseName("AK_User_Document");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("AK_User_Email");

                    b.HasIndex("FirstName", "LastName")
                        .HasDatabaseName("IX_User_FullName");

                    b.ToTable("User");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.UserAppClient", b =>
                {
                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.Property<Guid?>("AppClientId")
                        .HasColumnType("char(36)")
                        .HasColumnName("AppClientId");

                    b.HasKey("UserId", "AppClientId");

                    b.HasIndex("AppClientId");

                    b.ToTable("UserAppClient");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.UserCredential", b =>
                {
                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("AuthFailsQty")
                        .HasColumnType("int")
                        .HasColumnName("AuthFailsQty");

                    b.Property<ulong>("ChangeCredentials")
                        .HasColumnType("bit")
                        .HasColumnName("ChangeCredentials");

                    b.Property<DateTime?>("LockoutUntil")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("LockoutUntil");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(254)
                        .IsUnicode(false)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("Login");

                    b.Property<string>("Password")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)")
                        .HasColumnName("Password");

                    b.HasKey("UserId");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("AK_UserCredential_Login");

                    b.ToTable("UserCredential");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.UserCredentialToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ExpiresOn");

                    b.Property<ulong>("FirstAccess")
                        .HasColumnType("bit")
                        .HasColumnName("FirstAccess");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UserCredentialToken_UserId");

                    b.ToTable("UserCredentialToken");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("UserId");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.AppClient", b =>
                {
                    b.HasOne("RSoft.Auth.Infra.Data.Entities.User", "ChangedAuthor")
                        .WithMany("ChangedAppClients")
                        .HasForeignKey("ChangedBy")
                        .HasConstraintName("FK_AppClient_ChangedAuthor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RSoft.Auth.Infra.Data.Entities.User", "CreatedAuthor")
                        .WithMany("CreatedAppClients")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_AppClient_CreatedAuthor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedAuthor");

                    b.Navigation("CreatedAuthor");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.Role", b =>
                {
                    b.HasOne("RSoft.Auth.Infra.Data.Entities.AppClient", "AppClient")
                        .WithMany("Roles")
                        .HasForeignKey("ApplicationClientId")
                        .HasConstraintName("FK_Role_AppClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSoft.Auth.Infra.Data.Entities.User", "ChangedAuthor")
                        .WithMany("ChangedRoles")
                        .HasForeignKey("ChangedBy")
                        .HasConstraintName("FK_Role_ChangedAuthor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RSoft.Auth.Infra.Data.Entities.User", "CreatedAuthor")
                        .WithMany("CreatedRoles")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Role_CreatedAuthor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppClient");

                    b.Navigation("ChangedAuthor");

                    b.Navigation("CreatedAuthor");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.User", b =>
                {
                    b.HasOne("RSoft.Auth.Infra.Data.Entities.User", "ChangedAuthor")
                        .WithMany("ChangedUsers")
                        .HasForeignKey("ChangedBy")
                        .HasConstraintName("FK_User_ChangedAuthor")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RSoft.Auth.Infra.Data.Entities.User", "CreatedAuthor")
                        .WithMany("CreatedUsers")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_User_CreatedAuthor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedAuthor");

                    b.Navigation("CreatedAuthor");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.UserAppClient", b =>
                {
                    b.HasOne("RSoft.Auth.Infra.Data.Entities.AppClient", "ApplicationClient")
                        .WithMany("Users")
                        .HasForeignKey("AppClientId")
                        .HasConstraintName("FK_UserAppClient_AppClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSoft.Auth.Infra.Data.Entities.User", "User")
                        .WithMany("ApplicationClients")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserAppClient_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationClient");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.UserCredential", b =>
                {
                    b.HasOne("RSoft.Auth.Infra.Data.Entities.User", "User")
                        .WithOne("Credential")
                        .HasForeignKey("RSoft.Auth.Infra.Data.Entities.UserCredential", "UserId")
                        .HasConstraintName("FK_UserCredential_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.UserCredentialToken", b =>
                {
                    b.HasOne("RSoft.Auth.Infra.Data.Entities.User", "User")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserCredentialToken_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.UserRole", b =>
                {
                    b.HasOne("RSoft.Auth.Infra.Data.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_UserRole_Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RSoft.Auth.Infra.Data.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_UserRole_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.AppClient", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("RSoft.Auth.Infra.Data.Entities.User", b =>
                {
                    b.Navigation("ApplicationClients");

                    b.Navigation("ChangedAppClients");

                    b.Navigation("ChangedRoles");

                    b.Navigation("ChangedUsers");

                    b.Navigation("CreatedAppClients");

                    b.Navigation("CreatedRoles");

                    b.Navigation("CreatedUsers");

                    b.Navigation("Credential");

                    b.Navigation("Roles");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
