version: '2'

services:
  
  rsoft-mail:
    container_name: rsoftauth
    build: 
      context: .
      dockerfile: RSoft.Auth.Web.Api/Dockerfile
    image: rsoft/auth:1.0.0-rc
    ports: 
      - "5100:80"
    environment:  
      - ASPNETCORE_ENVIRONMENT=Production
    networks_mode: bridge